Feature/latest runtimes
tmobile/jazz pull request #1297
Opened 2020-10-22 05:09 UTC by SauarvD

### Requirements

* Updating latest runtimes in UI and supporting old runtimes along with new ones in backend

### Description of the Change

* Updated UI with latest runtimes
* Updated Jenkins build pack with latest runtimes and also supporting old runtimes as well

### Benefits

* User will be able to use the latest runtimes provided by AWS

### Possible Drawbacks

### Applicable Issues

2020-10-24 02:55 UTC, devsatishm commented
LGTM

2020-10-24 02:55 UTC, devsatishm approved these changes

2020-10-24 02:57 UTC, devsatishm commented
@SauarvD Missing changes in create-service & services API. They should be updated to support the new runtimes.

2020-10-24 02:58 UTC, devsatishm requested changes
Need changes.

2020-10-28 03:58 UTC, SauarvD commented
@devsatishm No changes are required for create-service & services API. We just need to update the allowed runtimes in the config DB. Once the stack is built, it will deploy the create-service & services API which will get updated with new runtimes

2020-10-28 04:28 UTC, devsatishm commented
> @devsatishm No changes are required for create-service & services API. We just need to update the allowed runtimes in the config DB. Once the stack is built, it will deploy the create-service & services API which will get updated with new runtimes

@SauarvD  Almost! Looks like one of the swaggers & a config file need an update. You can search for `python3` or `nodejs10` and make sure all the locations reflect the new changes.

2020-10-29 03:15 UTC, SauarvD commented
@devsatishm Done the changes

2020-10-29 03:16 UTC, SauarvD commented
> > @devsatishm No changes are required for create-service & services API. We just need to update the allowed runtimes in the config DB. Once the stack is built, it will deploy the create-service & services API which will get updated with new runtimes
> 
> @SauarvD Almost! Looks like one of the swaggers & a config file needs an update. You can search for `python3` or `nodejs10` and make sure all the locations reflect the new changes.

Done

2020-10-29 03:51 UTC, devsatishm approved these changes
Ship it!

2020-11-03 06:10 UTC, raghits reviewed
Other changes look good.

2020-11-03 06:10 UTC, raghits commented on builds/jenkins-build-pack-api/Jenkinsfile
> +    withEnv(["JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"]) {
These changes may not be needed if we manage to upgrade jenkins.

2020-11-03 06:10 UTC, raghits commented on builds/jenkins-build-pack-api/Jenkinsfile
> +    withEnv(["JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"]) {
These changes may not be needed if we manage to upgrade jenkins.

2020-11-03 06:10 UTC, raghits commented on builds/jenkins-build-pack-function/Jenkinsfile
> +    withEnv(["JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"]) {
These changes may not be needed if we manage to upgrade jenkins.

2020-11-03 06:10 UTC, raghits commented on builds/jenkins-build-pack-function/Jenkinsfile
> +    withEnv(["JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"]) {
These changes may not be needed if we manage to upgrade jenkins.

2020-11-03 06:10 UTC, raghits commented on builds/jenkins-build-pack-sls-app/Jenkinsfile
> +    withEnv(["JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"]) {
These changes may not be needed if we manage to upgrade jenkins.

2020-11-03 06:10 UTC, raghits commented on builds/jenkins-build-pack-sls-app/Jenkinsfile
> +    withEnv(["JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"]) {
These changes may not be needed if we manage to upgrade jenkins.

2020-11-03 21:14 UTC, devsatishm approved these changes

2020-11-03 21:53 UTC, raghits submitted a review, later dismissed
LGTM

2020-11-05 20:06 UTC, raghits approved these changes
LGTM

2020-11-05 20:17 UTC, devsatishm approved these changes

2020-11-05 20:18 UTC, merged